version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "aws-cdk-lib"
          - "constructs"
      production-dependencies:
        dependency-type: "production"
