name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/.setup.yml
      - uses: ./.github/workflows/.build.yml
