name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run commitlint -- --from ${{ github.event.pull_request.base.sha }} --verbose
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: npm run package
      - run: npm run documentation
