name: Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: cdk-skill-management

      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - if: ${{ steps.release.outputs.release_created }}
        name: Install
        run: npm ci
      - if: ${{ steps.release.outputs.release_created }}
        name: Lint
        run: npm run lint
      - if: ${{ steps.release.outputs.release_created }}
        name: Build
        run: npm run build
      - if: ${{ steps.release.outputs.release_created }}
        name: Test
        run: npm test
      - if: ${{ steps.release.outputs.release_created }}
        name: Package
        run: npm run package

      - if: ${{ steps.release.outputs.release_created }}
        name: Publish NPM
        run: npm publish dist/jsii/js/*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
