name: Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Package
        run: npm run package
      - name: Documentation
        run: |
          npm run docs
          git add --force ./docs/*

      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: cdk-skill-management

      - if: ${{ steps.release.outputs.release_created }}
        name: Publish NPM
        run: npm publish dist/jsii/js/*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - if: ${{ steps.release.outputs.release_created }}
        name: Publish PyPI
        run: |
          pip install twine
          twine upload dist/jsii/python/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_AUTH_TOKEN }}
